### ISSUE TITLE
Use some CSS to simplify presenter mode for slides

### ISSUE THREAD

**Issue by lesteve** [INRIA/scikit-learn-mooc#66]
Presenter mode is an easy way to show notes for remark.js slides. It does show things that we probably don't want to show for someone who is trying to read the slides:
- next slide and next slide notes
- timer

![image](https://user-images.githubusercontent.com/1680079/95846841-37d03680-0d4c-11eb-96cd-34493276f828.png)

@brospars if you had some time to look at this, it would be greatly appreciated!

Playing a bit with my modest CSS skills I can remove the elements with this CSS:
```css
.remark-notes-area .remark-bottom-area .remark-notes-preview-area {
 display: none;
}

.remark-preview-area .remark-slide-container {
    display: none;
}

.remark-toolbar .remark-toolbar-timer {
 display: none;
}
```

![image](https://user-images.githubusercontent.com/1680079/95848523-749d2d00-0d4e-11eb-828d-ff514e695ba4.png)

I would better if the main slide was taking the whole height though and I have to say I don't really know how easy this is.
